variable "renotify_after_hours_isolate" {
  type        = string
  description = "Number of hours to wait before AutoStop Lambda sends additional SNS notification(s)"
}

variable "renotify_after_hours_autostop" {
  description = "Number of hours to wait before AutoStop Lambda sends additional SNS notification(s)"
  type        = string
}

variable "idle_cpu_threshold" {
  description = "The CPU percentage that's indicative of an idle EC2 instance"
  type        = string
}

variable "idle_period_minutes" {
  description = "Time (in minutes) for an EC2 instance to remain idle before automatically being stopped"
  type        = string
}

variable "abuse_ipdb_api_key" {
  description = "The API key generated by AbuseIPDB"
  type        = string
}

variable "kms_key_arn" {
  description = "The ARN of the primary KMS key"
  type        = string
}

variable "ec2_isolate_lambda_to_sqs_json" {
  type        = string
  description = "JSON of the ec2_isolate_lambda_to_sqs policy"
}

variable "ec2_autostop_lambda_to_sqs_json" {
  description = "JSON of the ec2_autostop_lambda_to_sqs policy"
  type        = string
}

variable "ip_enrich_lambda_to_sqs_json" {
  description = "JSON of the ip_enrich_lambda_to_sqs policy"
  type        = string
}